server:
  port: 8080

spring:
 datasource:
  #url: jdbc:mysql://192.168.220.128:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
  url: jdbc:mysql://192.168.10.168:3306/basis-test?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
  #username: root
  username: root
  #password: Cj123456...
  password: xsq123456
  hikari:
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource
 redis:
   database: 1
   host: 192.168.10.168
   port: 9001
   password:
   lettuce:
     pool:
       #连接池最大的连接数
       max-active: 8
       #连接池最大阻塞等待时间
       max-wait: -1
       #最大空闲连接
       max-idle: 8
       #最小空闲连接
       min-idle: 0



logging:
  level:
    root: INFO
    com.anran.projectmanage.mapper: DEBUG

netty:
  websocket:
    port: 8000
    ip: 0.0.0.0
    path: /websocket
